language: python
dist: xenial

# Supported CPython versions:
# https://en.wikipedia.org/wiki/CPython#Version_history
python:
 - pypy3
 - pypy
 - "2.7"
 - "3.7"
 - "3.6"
 - "3.5"

install:
 - pip install flake8

script:
 # Static analysis
 - flake8 --statistics --count

matrix:
  fast_finish: true
