language: python

# Supported CPython versions:
# https://en.wikipedia.org/wiki/CPython#Version_history
python:
 - pypy3
 - pypy
 - "2.7"
 - "3.6"
 - "3.5"
 - "3.4"

sudo: false

install:
 - pip install pyflakes pycodestyle

script:
 # Static analysis
 - pyflakes . scripts/twolde
 - pycodestyle --statistics --count . scripts/twolde

matrix:
  fast_finish: true
